sudo: required

language: node_js

services:
  - docker
before_install:
  - docker-compose build
  - docker-compose run passwordkeeper npm run bild
  - docker-compose run passwordkeeper npm run test-unit
  - docker-compose run test-runner

