sudo: required
language: node_js
git:
  depth: 1
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

- docker --version
- docker-compose --version

- docker-compose pull frontend
- docker-compose build frontend
- docker-compose pull backend test-runner
- docker-compose build backend test-runner
install:
- docker-compose up -d test-server
script:
- docker-compose exec test-server npm run lint -- --max-warnings 0
- docker-compose up --exit-code-from karma-server karma-server karma-runner
- docker-compose run --rm test-runner
after_success:
- docker login -u="$DOCKER_HUB_USER" -p="$DOCKER_HUB_PASSWORD"
- docker-compose push frontend backend test-runner
env:
  global:
  - secure: COiArMZvGwbz+MHM0jM3vNlyaJWGv9STLxJZhX39NiYHMOI6GfvpIxKgGSdQHxCbOHzNBxn+EnX6AdNkFyLQTUIphiW3T4/rnN0jy/MDSjStiHLhmKfLyQtS17JXFYtUAHVoKBnmA82R9lNOhGY3cO7gqO0pOxwQjJqIrCN/nwyGwfaQ1Gg4e34VV0s1AUdSp+eSVnv0RUmvHQ7aeUbzcgs7IEcXBdkz1vbDCq3EJgc3xpNy/AXXod3jkPKtkkFtZ7s/oJogD0v3N6vvGDocBuEGe2cKof9E3Oteub0Ugg+wUrOrerWG9yXENIuwaRbB+egRivI62efTVh1Fp/YB2eSLzxyRK1K0BitpDG9G8/efTophHiMV6r2hgXMv4W9wDWndVaQdP9abusSzyDoz3ta+JqUOYx5hnjVb0cXSO1QgOff751qJWdL1VimBvK9mHj09dQEETJgAggR9lsUPoPN0pof3XI00+Rngc6L1PqhTheUQl4J/FOt4tcllICjgs1BOMNlgJaYYmuKRdNvi9+OaWUiJWqALagtLVjZexP+vBhbVGdvUbhxHzWFJgS6NvyJIjonGyV9mUuhl0M1i65ZdIrD4momNlYwFHMArgAy8X5Whps+Z5zSZhgJVbsK8lHFHSbAYfRxpHEJSHUIjMzpLHW24NZ/IY1MRJkFI+Lk=
  - secure: bCZlNg2rUsaeiGXMZJZCFeI5ZEdYJ+JUnaH1xSuHp3/sb1sSZkT6hxnTMLWorPUYScrc3JR+c6DRptU9r5A1NJyTR7KBa1sVd8l9TEPUKBZ+9vN7DzHCuQFP5mCmw93V2M6MZGgxeTBF7gt1M4vNUK/RYHu+/i0Aho9YoQOZ5sfZ91MsUY5DiIJf8VvMojLFu73NaM7RP3Lld+8u/ebypYIIqGByW1gj5Myi08n5lvvkTpu+EmVRaNpOPCEqpwFsOaL8Os7qZNXL5z+lhCyDCl7KsLRWWqEMNAgQUBa6fLMXroC7i4+KruaZ912UaByZP9VgQdYE2pRGJR+BHXC832hr8yXEy+oYVKn+LjTRVlUEBxrnu0Ui+cYJeTaCA/gPJ1S19H3RYtTGQH9deKQikbBR+ruaWua1yFQns1HU7/iAx1LYbrKM5iNRcpCESX7JsQQjmsaxTGzx/khWutarUaQ94sxVsh/y9rFZbBwmyNmYKLMyX7ZLSRqQOaJ90AOGpwm143nPNbN5B8we5C2B0MnpCLFW689ZMmb+1wbzuMu6rL24Ywknb051fdmAllxs4+0UliUo4sX4iaDZ3VVpaCSnhKtdBA0ydtPGbRnaznalSnVyD7tBuQnI55x9PTOogu+E6KFvMy9KlU86S9lX1pzkQq/zcQ08+cE8GUenmBE=
  - secure: YZcT2WWcQndw0AxDvKyD3vM5UVRrWwEj/8HabyzwkSAVs1wXQA1X1jlGwWxBXqKYjR6pmajuev7BX41SN93cpHS+k2plEWdOzIuI9HuWZ/dxrotPSUwvNyAQdMbpJv/Z8+1t7a70KddsWG7zNkwHNNUGAZ+WCSrqX/HyXDDVpoxezUw3Dwtgb6lShF9KjrSV1jUXdWE1rNauk4yhEugmIA/87d68NYdhr6Wu1/Y/Ij0te8iujm1hrOcl0BxfGSdszu39yveJsf9Ola3IftL6OAct6tnYvr+sfAQ9Ea1DQbhbmfSrN5oFyGoC0jBHjhVZJ4/mMAXxwltiv5nijWuZncZu52I2axBxUWOaYVQ834qS+cha4s8FkcMk9IgQ08MWTC9711Zx1KuV5uYZgem71A6ljB5I/ZFUE5AnzC/kVANJw8W1XGEmrV73rGKp+ysOCMWqN2wnAOTpNym66+u/axtvXa4NxzrrinEucLrk3nuP0FSCV4C6MS/BiJzTM4w5rGZd8qngQlhkTf5QmnFarbxP/+5eORzCPN2JgPXEYNZlOiq4rCc5lE6DbnWgskBq+U6WWJxWcbSKHB+Y5eaTBch0lmyIu0Dp2yYPPcK8PdAPvm0BGOcnRFfvwZLvN1hGuQAMCchzuwo5lAplweCSGWsh29RupbJPRhfGFW0l1Pk=
  - secure: elMTb+2XwXgG3FHxrW4Y+oHfuubEVH0aKDGPCy5hU/x/okGmoInsNwrAQl0DxXy+piZ6OoUG3eMi27SymfSCNwJAAIhBLgRRAzXjAfhFQOYnB0nSNND5WSS+dD4CSGdOaJv2+yqYbozZOaUA2joNLb49f3zh9e4NJM05p6B1nH9AMd7O8xb9spx5l2RPR7O39Ima4R32IQVesXWxQ0Wfqs6GXm6EtfP5j021srEWk3aK0W7A6aK2zwr+uwfIAovKartgSnPmaMUPaw8Cvb19arYMKuykx/EL5DIjw8gXfK+GFOj3EhILC/KgrJCm9qlarLI1EOp5B3Wj2XojopznwABCBHnKqII3fk/W95kH7nE5q7aqvZSucehsmV7487f+F28KYPG4Q6IEb+7Kot7YDocSkH/Q2WbmwCwPfHuagzxGmneyQXb7qeDwt3WUDtlbjwUfLnME3nxM4/gsu1RnnBPiBrh5rCFhstbCJ+D4llNxU9QlfEv8+XIUhmI7XY6mQgz9x0CdU5NMzfXn7ARvRLId9qd0FQBlIjw7A93i8mF0SeamEg8nQUuXhkIoZxbS2vCVtoJTQrEfSH8ZMjDvON5W9UvfQ1yG6vYJ2m6b3tEK/Syml5d3yXRaHX4G3pzcA5XS3dYvb+MdT9swmL3GvK6J3rdZ1ckWoOs2dJEuSyc=
  - secure: YgK+eTaTeyEBN9GpWV4sjP8vOzUgMerwyzVsqypH+DIfsDaLLzyJ8EGBKYgaef7ujcboD72i1o1Cl+ksJPq3UWFGC1Hz17CbGB/myZRy33IJtLgSGiXMqBKM5YaNAZlzBm2oWUsngEmOy4zLio7kSdAjSr0HXsJFIkD0aKfdv10FFmkOYTtZ7FDsgNeD7bCkcHdPMOZiGZrITQnHwoKE8x5fwVqrC9YL9IZzRAoDZcTOvqikuYIYNDi6CAYQxN/75mRWP1/SLnyPqb4bwzjNL/5lJPHsQgfHYI49kpYNt2gWkMOzj8vn1bYtzxlErkUMwopc8Z7QJLt7OQHey3kQ0g5mYiA8MpqsWQIdP4azkTsi3TbjEFzq1Aead5P86MXfws/XY4piLjJKkjWKj2Aec8yUnCyDVeTthLAHuizFH58tzFkxBCIaADJm7ettmZt01c9Ilx3kjUx22ZULwiuMKGLujJR0YR2GWHsLjI615xnLCZdO8y0nBDgPqI8dTci7B+wzxGQ1a2thwHAD3AscAgOC+NF8Ysf+msgdI9BdnY2RkLbjpSUhl3xMhj3L1uICJTNThB7x80ZW1oIihrtIV+NUNNVhetNXEZQOt+nRw9n8PZJDn3jWFS+9U2B3+10ZRt99qUlF6gvx3XT0ehWnf36LXPP1Wb2up7ncDs2TIDk=
notifications:
  slack:
    secure: q1kSyhC0oGvuae0PnMMC48T3XxUUi1QNnpwoCNF13KFAJGy1ZzR/k27EbrG4WsUTnZ9mPqDN8RuDEWJKk1+P1eN01KaSiPS963bbfAZV6fjPUehNayUoslBuahxOXrZ8uJm3rIfpCtr3/HzaVYG+JdHhW2cK3oZyLGksJp3llfdvej4StxSuGpA3lK8d7vmn/t01Q35L4pjRbBzxTCtfAqp0luI7NMVZadszXmTH5qEoHkZNL8ZEi37lS266lW7+kzc/L8CDQM9LCDIv/nnUUZZeaJOar2WqJtt/1mxzkruybWtbhznHVyCu7Xb4dpQEmoDJSvc8jTts7MDixOIFQyq2syqiOeZZm5vD+vI7DvnGQTDxnuLKyGMCPzFxTKKk3okbzlBwbD1jHbDRaFmNpkNbUjHjq/YG430VRT2Fp4pqdNkPbdY/aJi7fHsiuCpNKRREXnAnTcZ3ANGNN5XlcHkZ9VhkOtkF69mH7b6vDyj0BL17ZQ3b0DhAtvLSalyXmIMPy0gW8vboV/n10G9gpYeBzm1pYCCwOc/XOn25YCuIHLqytPraIRxJUDkSlqDQ8aVYSq1NrBm7w+uKQq7TWsxEhT47PNCktW8IMMVPXAuR3i906gXFWGyYNCgvOdVSqN4EF/Y2GhFmSuFn6VTxhTs/mCXES65S08vqt1FUCbI=
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x scripts/deploy.sh && scripts/deploy.sh
  on:
    branch: master
