FROM passwordkeeper/base:0.4

RUN apt-get install -y git

WORKDIR /usr/src/passwordkeeper/frontend

COPY frontend/package.json .
RUN npm install

COPY frontend .

ARG NODE_ENV
ENV NODE_ENV "$NODE_ENV"

RUN npm run build

CMD ["npm", "run", "build:watch"]
