FROM passwordkeeper/frontend as frontend

FROM passwordkeeper/base:0.5

ARG NODE_ENV
ENV NODE_ENV "$NODE_ENV"

WORKDIR /usr/src/passwordkeeper

COPY package.json .
RUN npm install

COPY backend backend
COPY --from=frontend /usr/src/passwordkeeper/frontend/dist frontend/dist

COPY scripts/launch.backend.sh ./scripts/launch.backend.sh
CMD ["bash", "./scripts/launch.backend.sh"]
