version: '2'

services:
  # NON-watch workflow
  postgres:
    image: postgres:latest
    environment:
     POSTGRES_USER: 'vagrant'
     POSTGRES_PASSWORD: 'vagrant'
     POSTGRES_DB: 'pkeeper'
  frontend:
    build:
     context: .
     dockerfile: Dockerfile.frontend
    volumes:
     - .:/usr/src/passwordkeeper
     - /usr/src/passwordkeeper/node_modules
    ports:
     - "35729:35729" # livereload
  backend:
    build:
     context: .
     dockerfile: Dockerfile.backend
    volumes:
     - .:/usr/src/passwordkeeper
     - /usr/src/passwordkeeper/node_modules
    ports:
     - "1337:1337" # main app port
     - "9229:9229" # node debug
    depends_on:
     - postgres
     - frontend
  # NON-watch tests
  test-server:
    build:
     context: .
     dockerfile: Dockerfile.backend
    image: passwordkeeper_backend
    ports:
     - "1337:1337" # port for testing app
    depends_on:
     - postgres
     - frontend
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    volumes:
      - ./e2e:/usr/src/passwordkeeper/e2e
      - /usr/src/passwordkeeper/e2e/node_modules
    depends_on:
      - test-server 
      - selenium
  selenium:
    image: selenium/standalone-chrome-debug
    expose:
     - "4444"
    ports:
     - 5900:5900
