FROM passwordkeeper/base

RUN apt-get install -y g++ build-essential
# Create app directory
WORKDIR /usr/src/passwordkeeper/e2e

# Install app dependencies
COPY e2e .
RUN npm install

COPY wait-for-it.sh ../
ENTRYPOINT ["bash", "../wait-for-it.sh", "-t", "30", "test-server:1337", "--"]
CMD ["npm", "run", "test"]
