passwordkeeper:
	build: .
	command: echo 'ready'
	volumes:
		- .:/usr/src/passwordkeeper
services:
	jre8:
		image: openjdk:8-jre
	postgres:
		image: postgres:latest
		environment:
			POSTGRES_USER: pkeeper
			POSTGRES_PASSWORD: pkeeper
			POSTGRES_DB