version: '3'

services:
  passwordkeeper:
    build: .
    volumes:
     - .:/usr/src/passwordkeeper
     - /usr/src/passwordkeeper/node_modules
    depends_on:
     - postgres
    ports:
     - "8000:8000"
     - "1337:1337"
     - "4444:4444"
     - "35729:35729"
     - "5858:5858"
     - "5900:5900"
    tty: true
  postgres:
    image: postgres:latest
    environment:
     POSTGRES_USER: 'vagrant'
     POSTGRES_PASSWORD: 'vagrant'
     POSTGRES_DB: 'pkeeper'