FROM passwordkeeper/base:0.4

RUN apt-get install -y g++ build-essential

# Create app directory
WORKDIR /usr/src/passwordkeeper/e2e

# Install app dependencies
COPY e2e/package.json .
RUN npm install

COPY e2e .
