FROM yukinying/chrome-headless-browser

COPY wait-for-it.sh ./

ENTRYPOINT ["bash", "./wait-for-it.sh", "-t", "120", "karma-server:9876", "--"]
CMD ["/usr/bin/dumb-init", "--", \
"/usr/bin/google-chrome-unstable", \
"--disable-gpu", \
"--headless", \
"--remote-debugging-address=0.0.0.0", \
"--remote-debugging-port=9222", \
"--user-data-dir=/data", \
"http://karma-server:9876"]
