version: '3'

services:
  passwordkeeper:
    build: .
    volumes:
     - .:/usr/src/passwordkeeper
    depends_on:
     - postgres
    ports:
     - "8000:8000"
     - "1337:1337"
    tty: true
  postgres:
    image: postgres:latest
    environment:
     POSTGRES_USER: 'vagrant'
     POSTGRES_PASSWORD: 'vagrant'
     POSTGRES_DB: 'pkeeper'