version: '2'

services:
  passwordkeeper:
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
     - .:/usr/src/passwordkeeper
     - /usr/src/passwordkeeper/node_modules
    depends_on:
     - postgres
    environment:
     NODE_ENV: development
    ports:
     - "1337:1337"
     - "4444:4444"
     - "35729:35729"
     - "9229:9229"
     - "5900:5900"
  web:
    build:
     context: .
    volumes:
     - .:/usr/src/passwordkeeper
     - /usr/src/passwordkeeper/node_modules
    depends_on:
     - postgres
    environment:
     NODE_ENV: production
    ports:
     - "1337:1337"
     - "4444:4444"
     - "35729:35729"
     - "9229:9229"
     - "5900:5900"
  postgres:
    image: postgres:latest
    environment:
     POSTGRES_USER: 'vagrant'
     POSTGRES_PASSWORD: 'vagrant'
     POSTGRES_DB: 'pkeeper'
  test-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - .:/usr/src/passwordkeeper
     - /usr/src/passwordkeeper/node_modules
    environment:
     NODE_ENV: development
    depends_on:
     - postgres
    expose:
     - "1337"
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./e2e:/e2edocker
    command: npm run test-e2e
    depends_on:
      - test-server
      - postgres
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug
    expose:
     - "4444"
    ports:
     - 5901:5900